Ext.define('AppIndex.view.AppHome',{
    extend:'Ext.container.Container',
    xtype:'app_home',
    controller:'home',
    requires:[
        'AppIndex.controller.AppHomeController',
        'AppIndex.view.AppHeader',
        'AppIndex.view.AppWest',
        'AppIndex.view.AppCenter',
        'AppIndex.view.SalesOrderNoteView',
        'AppIndex.view.SalesNoteView',
        'AppIndex.view.PurchaseNoteView',
        'AppIndex.view.StorageInView',
        'AppIndex.view.RoleManagerView'
    ],

    layout:{
        type:'border'
    },

    items:[
        {
            region:'north',
            xtype:'app_header'
        },
        {
            region:'west',
            xtype:'app_west'
        },
        {
            region:'center',
            xtype:'app_center'
        }
    ]
});